image: sikalabs/ci

stages:
  - build
  - test
  - deploy dev
  - deploy prod

build bin:
  stage: build
  image: golang
  script:
    - echo $GOOS $GOARCH
    - go build server.go
  parallel:
    matrix:
      - GOOS:
        - darwin
        - linux
        - windows
        GOARCH:
        - amd64
        - arm64
  artifacts:
    public: true
    paths:
      - server
      - server.exe

build docker:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
