image: sikalabs/ci

variables:
  HOST: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID

stages:
  - build
  - deploy dev
  - test
  - deploy prod

build bin:
  stage: build
  image: golang
  script:
    - echo $GOOS $GOARCH
    - go build server.go
  parallel:
    matrix:
      - GOOS:
        - darwin
        - linux
        - windows
        GOARCH:
        - amd64
        - arm64
  artifacts:
    public: true
    paths:
      - server
      - server.exe

build docker:
  stage: build
  dependencies: []
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE

deploy dev:
  stage: deploy dev
  dependencies: []
  script:
    - helm repo add sikalabs https://helm.oxs.cz
    - helm upgrade --install $CI_COMMIT_REF_SLUG sikalabs/one-image
        --set image=$IMAGE
        --set host=$HOST
        --set www_redirect=false
        --set containerPort=8000
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    url: https://$HOST
    kubernetes:
      namespace: example
    on_stop: stop dev
  needs:
    - build docker

stop dev:
  stage: deploy dev
  dependencies: []
  when: manual
  variables:
    GIT_STRATEGY: none
  script:
    - helm uninstall $CI_COMMIT_REF_SLUG
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    action: stop
    kubernetes:
      namespace: example

test:
  stage: test
  dependencies: []
  script:
    - curl -fsSL -k https://$HOST
  needs:
    - deploy dev
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    action: prepare
